Controllers/ArchivosController.cs
using Microsoft.AspNetCore.Mvc;

namespace frontendnet;

public class ArchivosController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

}

Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Acceso denegado";
}

<div class="container">
    <h1 class="text-danger">@ViewData["Title"]</h1>
    <p class="text-muted">El usuario actual no tiene acceso a este apartado.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="~/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Peliculas Fei">
    <title>Netflix: @ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    @if(User.Identity?.IsAuthenticated == true)
    {
        <link rel="stylesheet" href="~/css/site.css" />
    }
    else
    {
        <link rel="stylesheet" href="~/css/guest.css" />
    }
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md bg-transparent">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index" >
                    <img alt="Inicio" src="~/images/logo.png" height="25" >
                </a>
                <button class="navbar-toggler shdow-none border-0 btn btn-light" type="button" data-bs-toggle="collapse"
                data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" 
                aria-label="Toggle navigation">
                <i class="bi bi-three-dots"></i>
                </button>
                <div class="navbar-collapse collapse">
                    <partial name="_MenuIzqPartial" />
                    <partial name="_MenuDerPartial" />
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="mt-3 mb-5 container">
        @RenderBody()
    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/cambio_tema.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuDerPartial.cshtml
<div class="navbar-nav small">
    <div class="navbar-text form-check form-switch form-check-reverse me-2">
        <input class="form-check-input" type="checkbox" id="darkModeSwitch">
        <label class="form-check" for="darkModeSwitch">
            <i class="bi bi-moon-stars modo-luz"></i>
        </label>
    </div>
    @if (User.Identity?.IsAuthenticated == true)
    {
        <a class="nav-link" asp-controller="Perfil">Hola @(User.Identity.Name)!</a>
        <a class="nav-link" asp-controller="Auth" asp-action="Salir">Salir</a>
    }
    else
    {
        <a class="nav-link" asp-controller="Auth" asp-action="Index">Iniciar sesión</a>
    }
</div>

Views/Shared/_MenuIzqPartial.cshtml
@using System.Security.Claims

<div class="me-auto navbar-nav">
    @if (User.Identity?.IsAuthenticated == true)
    {
        <a class="nav-link" asp-controller="Home" asp-action="Index">Inicio</a>
        <a class="nav-link" asp-controller="Peliculas" asp-action="Index">Peliculas</a>
        @if (User.FindFirstValue(ClaimTypes.Role) == "Administrador")
        {
            <a class="nav-link" asp-controller="Categorias" asp-action="Index">Categorias</a>
            <a class="nav-link" asp-controller="Archivos" asp-action="Index">Archivos</a>
            <a class="nav-link" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
            <a class="nav-link" asp-controller="Bitácora" asp-action="Index">Bitácora</a>
        }
    }
</div>